### ISSUE TITLE
Question: setTimeout or setInterval heartbeat

### ISSUE THREAD

**Issue by ciwox** [usamaejaz/my_shoutbox#1]
Is there anyway to change the hearbeat? Make it a little slower. It's flooding my server at the moment. I tried to change it in the original .js files but It looks like it doesn't make a difference. Where am I going wrong?

Thanks

**Comment by usamaejaz** [comment]
Hi. If you are using the chat_full.js, you have to edit the timeout by finding the following lines:

``` javascript
setTimeout(chat_heartbeat(), 100);
```

and this:

``` javascript
setTimeout(getChatterName(), 100);
```

Note the `100` milliseconds here.

If you are using chat.js (minimize-able chatbox):

``` javascript
setInterval(function(){
    if(!$(".chat_wrapper").is(".minimized_chat")){
        if(start==0){
            chat_heartbeat();
            getChatterName();
        }
    }
},500);
```

Note the `500` milliseconds here.

**Comment by ciwox** [comment]
Its weird because I changed both setTimeout's to 10000  //10 seconds, 
and it's still refreshing 2times per seconds. I also changed the chat.js's just to be sure but nothing helps.

``` javascript
setTimeout(chat_heartbeat(), 10000);
},
  error:function(){
    chat_heartbeat();
  }
});
}
function getChatterName(){
$.ajax({
  type: 'GET',
  url: base_url+'misc.php?action=getname',
  success:function(data){
    chatter=$("#chatform #chatter_name");
    if(data!=''){
        if(!(chatter.attr("disabled"))){
            chatter.val(data).attr("disabled","disabled");
        }
    } else {
        if((chatter.attr("disabled"))){
            chatter.removeAttr("disabled");
        }
    }
    setTimeout(getChatterName(), 10000);
  },
  error:function(){
    getChatterName();
  }
});
}
```

See screenshot: Notice the seconds please.
http://prntscr.com/9hvtlo

**Comment by usamaejaz** [comment]
Apologies. The setTimeout function call was mistakenly wrong (in a way). I have fixed that. The fix was to wrap the function name i.e `chat_heartbeat()` and `getChatterName()` in an anonymous function.

So, changing **from**:

``` javascript
setTimeout(chat_heartbeat(), 10000);
```

and

``` javascript
    setTimeout(getChatterName(), 10000);
```

**to**:

``` javascript
setTimeout(function(){ chat_heartbeat(); }, 10000);
```

and

``` javascript
    setTimeout(function(){ getChatterName(); }, 10000);
```

will fix the problem. 

I have pushed the changes and added a [new release](https://github.com/usamaejaz/my_shoutbox/releases/tag/1.2).

**Comment by ciwox** [comment]
Yes this works! Thanks alot Usama! :-) :+1:
